#!/bin/bash
#Note: execute the following way remotely
#bash <(wget -qO - https://raw.githubusercontent.com/jason75023/chef/master/chefbootstrapprep)
#Prepare a openstack node for chef bootstrap 

#allow root user login with password 
cd /etc/ssh
sed -i.bak -e 's/^#PermitRootLogin/PermitRootLogin/' -e 's/^#PasswordAuthentication/PasswordAuthentication/' sshd_config

echo "##### check sshd_config change ######"
diff sshd_config sshd_config.bak

read -p "Enter Password > " text 

#change password
echo -e "$text\n$text" | (passwd --stdin $USER)

#recycle sshd process
service sshd restart

