#!/bin/bash
#
#install nova client on centos linux server  
#usage:
#1. login to server 
#2.bash <(wget -qO - https://raw.githubusercontent.com/jason75023/chef/master/nova_install)

#Turn on EPEL repository
#cd /tmp
#wget http://mirror-fpt-telecom.fpt.net/fedora/epel/6/i386/epel-release-6-8.noarch.rpm
#rpm -ivh epel-release-6-8.noarch.rpm
rpm -ev epel-release-6-8.noarch
yum update
rpm -ivh http://dl.fedoraproject.org/pub/epel/6/$(uname -i)/epel-release-6-8.noarch.rpm

#install python package manager
yum install python-pip python-devl  libxml2-devel libxslt-devel
#install gcc
yum install gcc
#install nova client , keystone client, neutronclient 
pip install python-novaclient python-keystoneclient python-neutronclient 
